---
title: "Func data wrangling for HTN"
author: "Li- Fang Yeo"
date: "2024-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```
```{r}
#Functional pathways from metaCyc
joined_pathabundance <- read_delim("../data/joined_pathabundance.tsv", 
                                   delim = "\t", escape_double = FALSE, trim_ws = TRUE)
```
Data wrangling and cleaning up
```{r}
#Defining covariates for the model
vars <- list(BL_AGE = "Age",
             MEN = "Men",
             BMI = "BMI",
             PREVAL_DIAB.col_from_endpoints = "Diabetes",
             SYSTM = "Systolic blood pressure",
             BP_TREAT = "Antihypertensive medication",
             PREVAL_HFAIL_STRICT.col_from_endpoints = "Heart failure",
             PREVAL_CKD = "Prevalent CKD",
             INCIDENT_CKD = "Incident CKD",
             CKD_AGEDIFF = "CKD Agediff",
             CURR_SMOKE = "Smoking",
             PREVAL_AUTOIMMUN.col_from_endpoints = "Autoimmune disease",
             KREA_ENTS = "Creatinine",
             GFR = "Glomerulal filtration rate",
             UAC = "Urine Albumin-Creatinine Ratio",
             EAST = "Eastern Finland") 
#Importing metadata and cleaning up
tse <- readRDS("data/tse_gg2_MGS_FR02.rds") %>%
  tse_mutate(dplyr::across(c(MEN,
                             EAST,
                             BP_TREAT,
                             CURR_SMOKE,
                             dplyr::contains("INCIDENT"),
                             dplyr::contains("PREVAL")), as.factor)) %>% 
  tse_mutate(GFR = 0.993^round(BL_AGE) *
               dplyr::case_when(MEN == 0 & KREA_ENTS <= 62 ~ 144*(KREA_ENTS/61.9)^-0.329,
                                MEN == 0 & KREA_ENTS >  62 ~ 144*(KREA_ENTS/61.9)^-1.209,
                                MEN == 1 & KREA_ENTS <= 80 ~ 141*(KREA_ENTS/79.6)^-0.411,
                                MEN == 1 & KREA_ENTS >  80 ~ 141*(KREA_ENTS/79.6)^-1.209)) %>%
  tse_mutate(UAC = U_ALB/U_KREA) %>% 
  tse_filter(GRAVID %in% c(1, NA), BL_USE_RX_J01_1mo %in% c(0, NA)) %>%
  tse_filter(dplyr::if_all(dplyr::one_of(names(vars) %difference% "UAC"), not_na)) %>%
  tse_select(names(vars))
#Matching sampleID from functional data to metadata
#rename 1st column name
a <- as.data.frame(colData(tse))%>%
  tibble::rownames_to_column("Barcode")

# Get the column names (excluding the first one, which is probably the path/feature column)
sample_names <- colnames(joined_pathabundance)[-1]

# Clean sample names by removing after .R1
cleaned_sample_names <- gsub("\\.R1.*","", sample_names, perl = TRUE)

# Update the column names with the cleaned sample names
colnames(joined_pathabundance)[-1] <- cleaned_sample_names

# Find the intersection of sample names between the cleaned joined_path_abundance sample names and FINRISK sample data
common_samples <- intersect(a$Barcode, cleaned_sample_names)

# Subset the joined_pathabundance file to include only the common samples
joined_pathabundance<- joined_pathabundance %>%
  select(all_of(c("Pathway", common_samples)))

```
Filtering any pathways associated w/ species
```{r}
#Analysis focused on finding species pathways
shit<- joined_pathabundance %>% 
  filter(rowSums(across(where(is.numeric)))!=0) %>%
  #grep all Pathways that end with species
  filter(grepl('.s__', Pathway))
```
Calculating coefficient of variance
```{r}
#calculate standard coefficient variation by row-wise feature
#shit %>%
 # rowwise() %>%
#  mutate(
 #   mean_val = mean(c_across(2:6567)),
  #  sd_val = sd(c_across(2:6567)),
   # cv = (sd_val / mean_val) * 100) %>%
#  ungroup() %>%
 # hist(cv)
```
Transpose dataframe
```{r}
shit.t <- as.data.frame(t(shit))
#take first row as colname
colnames(shit.t) <- shit.t[1,]
#remove extra row
shit.t <- shit.t[-1, ] 
#change from character to numeric
shit.t <- shit.t %>% mutate_if(is.character, as.numeric) %>%
  tibble::rownames_to_column("Barcode") 
```
```{r}
write_rds(shit.t, "path.abund.t.rds")
write_rds(shit, "path.abund.rds")
```